version: '3.8'

services:
  backend:
    build: 
      context: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@db/cocktaildb
    depends_on:
      - db
    command: sh -c "pip install . && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"

  frontend:
    build: 
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=cocktaildb
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    # Ajout d'un healthcheck
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d cocktaildb"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local